library(shiny)
library(shinydashboard)

ui <- dashboardPage(skin = "blue",
                    dashboardHeader(title = "cranExplr"),
                    dashboardSidebar(sidebarMenu(
                       menuItem("Simulator",
                                tabName = "simulator",
                                icon = icon("gears")),
                       menuItem("Manual",
                                tabName = "manual",
                                icon = icon("tachometer")),
                       menuItem("About",
                                tabName = "about",
                                icon = icon("graduation-cap")))
                    ),
                    dashboardBody(
                       tabItems(
                          tabItem(tabName = "about",
                                  h1("Using cranial metrics to explore ancestry"),
                                  br(),
                                  h4("How to use:"),
                                  p("In the side menu, you will find the Simulator tab,
                                    which allows you, through 29 classic cranial measurements, to 
                                    understand how morphology influences the probability
                                    of belonging to a specific population (or the other way around!).
                                    This is accomplished through a dataset of 3163 crania
                                    from 74 worldwide samples, which were measured in 29
                                    parameters (check these in the Manual tab).
                                    This dataset was obtained from the cranID software
                                    (Wright, 2012). Using a simple machine learning algorithm
                                    it was possible to create a prediction function which reactively
                                    generates a barplot of probabilities."),
                                  br(),
                                  h4("Classification Model:"),
                                  p("Flexible Discriminant Analysis."),
                                  br(),
                                  h4("Code & App Development:"),
                                  p("João Coelho, M.Sc."),
                                  p("joao@osteomics.com"),
                                  p("Department of Life Sciences, University of Coimbra, Portugal"),
                                  p("osteomics.com, Instituto Pedro Nunes"),
                                  br(),
                                  h4("Reference:"),
                                  p("Wright R. 2012.  Guide to using the CRANID programs CR6bIND:
                                    For linear and nearest neighbours discriminant analysis.",
                                    em("https://www.box.net/shared/static/qyaq6thdds.pdf"))
                          ),
                          tabItem(tabName = "manual",
                                  fluidPage(box(collapsible = TRUE,
                                                img(src = "1.png", width=400),
                                                br(),
                                                strong("1. GOL Glabello-occipital length"),
                                                p("Greatest length, from the glabellar region, in the median sagittal plane."),
                                                strong("2. NOL Nasio-occipital length"),
                                                p("Greatest cranial length in the median sagittal plane, measured from nasion."),
                                                strong("3. BNL Basion-nasion length"),
                                                p("Direct length between basion and nasion."),
                                                strong("4. BBH Basion-bregma height"),
                                                p("Distance from basion to bregma, as defined."),
                                                strong("9. BPL Basion-prosthion length"),
                                                p("The facial length from basion to prosthion, as defined.")),
                                            box(collapsible = TRUE,
                                                img(src = "2.png", width=400),
                                                br(),
                                                strong("5. XCB Maximum cranial breadth"),
                                                p("The maximum cranial breadth perpendicular to the median sagittal plane (above the supramastoid crests)."),
                                                strong("6. XFB Maximum frontal breadth"),
                                                p("The maximum breadth at the coronal suture, perpendicular to the medial plane."),
                                                strong("14. JUB Bijugal breadth"),
                                                p("The external breadth across the malars at the jugalia, i.e., at the deepest points in the curvature between the frontal and temporal process of the malars."),
                                                strong("17. ZMB Bimaxillary breadth"),
                                                p("The breadth across the maxillae, from one zygomaxillare [anterior] to the other.")),
                                            box(collapsible = TRUE,
                                                img(src = "3.png", width=400),
                                                br(),
                                                strong("7. AUB Biauricular breadth"),
                                                p("The least exterior breadth across the roots of the zygomatic processes, wherever found."),
                                                strong("8. ASB Biasterionic breadth"),
                                                p("Direct measurement from one asterion to the other."),
                                                strong("16. MAB Palate breadth, external"),
                                                p("The greatest breadth across the alveolar borders, wherever found, perpendicular to the median plane.")),
                                            box(collapsible = TRUE,
                                                img(src = "4.png", width=400),
                                                br(),
                                                strong("10. NPH Nasion-prosthion height"),
                                                p("Upper facial height from nasion to prosthion, as defined."),
                                                strong("11. NLH Nasal height"),
                                                p("The average height from nasion to the lowest point on the border of the nasal aperture on either side."),
                                                strong("15. NLB Nasal breadth"),
                                                p("The distance between the anterior edges of the nasal aperture at its widest extent."),
                                                strong("19. FMB Bifrontal breadth"),
                                                p("The breadth across the frontal bone between frontomalare anterior on each side, i.e., the most anterior point on the fronto-malar suture."),
                                                strong("23. WMH Cheek height"),
                                                p("The minimum distance, in any direction, from the lower border of the orbit to the lower margin of the maxilla, mesial to the masseter attachment, on the left side.")),
                                            box(collapsible = TRUE,
                                                img(src = "5.png", width=400),
                                                br(),
                                                strong("12. OBH Orbit height, left"),
                                                p("The height between the upper and lower borders of the left orbit, perpendicular to the long axis of the orbit and bisecting it."),
                                                strong("13. OBB Orbit breadth, left"),
                                                p("Breadth from ectoconchion to dacryon, as defined, approximating the longitudinal axis which bisects the orbit into equal upper and lower parts."),
                                                strong("21. EKB Biorbital breadth"),
                                                p("The breadth across the orbits from ectoconchion to ectoconchion."),
                                                strong("22. DKB Interorbital breadth"),
                                                p("The breadth across the nasal space from dacryon to dacryon."),
                                                br(),
                                                h4("Not defined in any image:"),
                                                strong("18. SSS Zygomaxillary subtense"),
                                                p("The projection or subtense from subspinale to the bimaxillary width [ZMB]."),
                                                strong("20. NAS Nasio-frontal subtense"),
                                                p("The subtense from nasion to the bifrontal breadth.")),
                                            box(collapsible = TRUE,
                                                img(src = "6.png", width=400),
                                                br(),
                                                strong("24. FRC Nasion-bregma chord (Frontal chord)"),
                                                p("The frontal chord, or direct distance from nasion to bregma, taken in the midplane and at the external surface."),
                                                strong("25. FRS Nasion-bregma subtense (Frontal subtense)"),
                                                p("The maximum subtense, at the highest point on the convexity of the frontal bone in the midplane, to the nasion-bregma chord."),
                                                strong("26. PAC Bregma-lambda chord (Parietal chord)"),
                                                p("The external parietal chord, or direct distance from bregma to lambda, taken in the midplane and at the external surface."),
                                                strong("27. PAS Bregma-lambda subtense (Parietal subtense)"),
                                                p("The maximum subtense, at the highest point on the convexity of the parietal bones in the midplane, to the bregma-lambda chord."),
                                                strong("28. OCC Lambda-opisthion chord (Occipital chord)"),
                                                p("The external occipital chord, or direct distance from lambda to opisthion, taken in the midplane and at the external surface."),
                                                strong("29. OCS Lambda-opisthion subtense (Occipital subtense)"),
                                                p("The maximum subtense, at the most prominent point on the basic contour of the occipital bone in the midplane.")
                                                ))
                          ),
                          tabItem(tabName = "simulator",
                                  #fluidPage(fluidRow(ggvisOutput("ggvis"))),
                                  fluidPage(fluidRow(box(plotOutput("plot")),
                                                     tabBox("tabset1", height = "200px",
                                                            tabPanel("GOL", sliderInput("GOL", "Glabello-occipital length",
                                                                                        min = 150, max = 207, value = 179)),
                                                            tabPanel("NOL", sliderInput("NOL", "Nasio-occipital length:",
                                                                                        min = 150, max = 203, value = 177)),
                                                            tabPanel("BNL", sliderInput("BNL", "Basion-nasion length:",
                                                                                        min = 81, max = 121, value = 99)),
                                                            tabPanel("BBH", sliderInput("BBH", "Basion-bregma height:",
                                                                                        min = 106, max = 155, value = 132)),
                                                            tabPanel("XCB", sliderInput("XCB", "Maximum cranial breadth:",
                                                                                        min = 112, max = 168, value = 137)),
                                                            tabPanel("XFB", sliderInput("XFB", "Maximum frontal breadth:",
                                                                                        min = 91, max = 126, value = 114)),
                                                            tabPanel("AUB", sliderInput("AUB", "Biauricular breadth (AUB):",
                                                                                        min = 97, max = 154, value = 120))
                                                     ),
                                                     tabBox("tabset2", height = "200px",
                                                            tabPanel("ASB", sliderInput("ASB", "Biasterionic breadth (ASB):",
                                                                                        min = 87, max = 129, value = 107)),
                                                            tabPanel("BPL", sliderInput("BPL", "Basion-prosthion length (BPL):",
                                                                                        min = 78, max = 124, value = 97)),
                                                            tabPanel("NPH", sliderInput("NPH", "Nasion-prosthion height (NPH):",
                                                                                        min = 47, max = 88, value = 66)),
                                                            tabPanel("NLH", sliderInput("NLH", "Nasal height (NLH):",
                                                                                        min = 35, max = 66, value = 50)),
                                                            tabPanel("OBH", sliderInput("OBH", "Orbit height (OBH):",
                                                                                        min = 25, max = 42, value = 34)),
                                                            tabPanel("OBB", sliderInput("OBB", "Orbit breadth (OBB):",
                                                                                        min = 32, max = 47, value = 39)),
                                                            tabPanel("JUB", sliderInput("JUB", "Bijugal breadth (JUB):",
                                                                                        min = 92, max = 139, value = 115))
                                                     )
                                  ),
                                  fluidRow(
                                     tabBox("tabset3", height = "200px",
                                            tabPanel("NLB", sliderInput("NLB", "Nasal breadth (NLB):",
                                                                        min = 17, max = 36, value = 26)),
                                            tabPanel("MAB", sliderInput("MAB", "Palate breadth, external (MAB):",
                                                                        min = 46, max = 80, value = 63)),
                                            tabPanel("ZMG", sliderInput("ZMB", "Bimaxillary breadth (ZMB):",
                                                                        min = 56, max = 121, value = 94)),
                                            tabPanel("SSS", sliderInput("SSS", "Zygomaxillary subtense (SSS):",
                                                                        min = 10, max = 37, value = 23)),
                                            tabPanel("FMB", sliderInput("FMB", "Bifrontal breadth (FMB):",
                                                                        min = 80, max = 113, value = 97)),
                                            tabPanel("NAS", sliderInput("NAS", "Nasio-frontal subtense (NAS):",
                                                                        min = 7, max = 28, value = 17)),
                                            tabPanel("EKB", sliderInput("EKB", "Biorbital breadth (EKB):",
                                                                        min = 82, max = 114, value = 97))
                                     ),
                                     tabBox("tabset4", height = "200px",
                                            tabPanel("DKB", sliderInput("DKB", "Interorbital breadth (DKB):",
                                                                        min = 11, max = 33, value = 22)),
                                            tabPanel("WMH", sliderInput("WMH", "Cheek height (WMH):",
                                                                        min = 12, max = 36, value = 22)),
                                            tabPanel("FRC", sliderInput("FRC", "Nasion-bregma chord (FRC):",
                                                                        min = 91, max = 129, value = 109)),
                                            tabPanel("FRS", sliderInput("FRS", "Nasion-bregma subtense (FRS):",
                                                                        min = 15, max = 36, value = 26)),
                                            tabPanel("PAC", sliderInput("PAC", "Bregma-lambda chord (PAC):",
                                                                        min = 88, max = 136, value = 111)),
                                            tabPanel("PAS", sliderInput("PAS", "Bregma-lambda subtense (PAS):",
                                                                        min = 12, max = 37, value = 24)),
                                            tabPanel("OCC + OCS", sliderInput("OCC", "Lambda-opisthion chord (OCC):",
                                                                              min = 60, max = 119, value = 95),
                                                     sliderInput("OCS", "Lambda-opisthion subtense (OCS):",
                                                                 min = 14, max = 43, value = 28))
                                     )
                                  )
                                  )
                          )
                       )
                    )
)
